server:
  port: 8080
  
jwt:
  secret: dadsnrgsthghdjgmdhgxfxmgfdyjmhgtxgdcjbngkjghchhfjdlshvfishdvuhzsuhvujksdbvkub
  
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
            exposedHeaders: '*'
      routes:
        - id: authentication-service
          uri: http://localhost:8082/
          predicates:
            - Path=/authentication-service/**
          filters:
            - RewritePath=/authentication-service(?<segment>/?.*), $\{segment}

        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service(?<segment>/?.*), $\{segment}

        - id: menu-service
          uri: http://localhost:9001/
          predicates:
            - Path=/menu-service/**
          filters:
            - RewritePath=/menu-service(?<segment>/?.*), $\{segment}

        - id: notification-service
          uri: http://localhost:8083/
          predicates:
            - Path=/notification-service/**
          filters:
            - RewritePath=/notification-service(?<segment>/?.*), $\{segment}

        - id: order-service
          uri: http://localhost:8087/
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service(?<segment>/?.*), $\{segment}

        - id: payment-service
          uri: http://localhost:9002/
          predicates:
            - Path=/payment-service/**
          filters:
            - RewritePath=/payment-service(?<segment>/?.*), $\{segment}

        - id: subscription-service
          uri: http://localhost:8086/
          predicates:
            - Path=/subscription-service/**
          filters:
            - RewritePath=/subscription-service(?<segment>/?.*), $\{segment}
            
        - id: product-webapp
          uri: http://localhost:4200/
          predicates:
            - Path=/**
          filters:
            - RewritePath=(?<segment>/?.*), $\{segment}

